name: itg_notes
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.3
  flutter_bloc: ^7.3.2
  shared_preferences: ^2.0.9
  http: ^0.13.4
  dartz: ^0.10.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  get_it: ^7.2.0
  bloc_test: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
